server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
      routes:
        - id: oauth-server
          uri: lb://oauth-server
          predicates:
            # 转发该路径
            - Path=/auth/**
          # 带前缀
          filters:
            - StripPrefix=1
        - id: mybatis-rw
          uri: lb://mybatis-rw
          predicates:
            # 转发该路径
            - Path=/mybatis/**
          # 带前缀
          filters:
            - StripPrefix=1
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: replace-with-client-id
            client-secret: replace-with-client-secret
            scope: read:user,public_repo
#security:
#  oauth2:
#    resource:
#      user-info-uri:  http://auth/user
#      prefer-token-info: false
#      service-id: oauth-server
#    client:
#      access-token-uri: http://auth/oauth/token
#      user-authorization-uri: http://auth/oauth/authorize

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
